import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { env } from "~/env.mjs";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        {env.NEXT_PUBLIC_PROD && (
          <script
            async
            defer
            data-website-id="afd4eaa8-bc88-43f3-9113-4bf407740756"
            src="https://umami.finndore.dev/script.js"
          ></script>
        )}
      </head>

      <body className={`font-sans ${inter.variable}`}>{children}</body>
    </html>
  );
}
